### ISSUE TITLE
Could You Share the Cross-Datasets Training Config for Reproduction?

### ISSUE THREAD

**Issue by Even-ok** [ZjjConan/Multi-Modal-Adapter#3]
I am trying to reproduce the MMAdapter cross-dataset results and followed the Implementation Details from the paper:

> For the other two experiment settings, similar to MaPLe [33], we set k = 9 and train our models just for 1 epoch.

My configuration .yaml file is as follows:

```
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0015
  MAX_EPOCH: 1
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 0
  WARMUP_TYPE: "linear"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MMADAPTER:
    TEXT_CTX_INIT: "a photo of a"
    ADAPTER_START: 9
    ADAPTER_END: 12
    ADAPTER_DIM: 32
    ADAPTER_SCALE: 0.001
    PREC: "amp"

```

With this, my results on ImageNet-val are:
Seed 1: 70.4
Seed 2: 70.5
Seed 3: 70.3
However, the reported result in the paper is 71.00. Could you please share your configuration file for the cross-datasets setting to help with reproduction?

Thank you!
